---
all:
  vars:
   ansible_ssh_private_key_file: "/home/user/.ssh/id_ed25519"  # Dynamic path to private key
  children:
    MINIO:
      hosts:
        minio:
          ansible_host: HOST_IP_ADDRESS
          ansible_port: HOST_PORT
          ansible_user: ANSIBLE_USER
          ansible_become: yes
          ansible_become_method: sudo
      vars:
        # app_name: "{{ ansible_hostname }}"
        app_name: "minio"
